name: Build and Deploy to GKE

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GCP_PROJECT_ID: todo-app-453916
  GCP_REGION: europe-central2-a
  GAR_REPOSITORY: todo-api

  IMAGE_NAME: todo-api:latest
  IMAGE_TAG: latest
  GKE_CLUSTER: todo-app
  GKE_REGION: europe-central2-a

  GCP_SA_JSON: ${{ secrets.GCP_SA_JSON }}

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${GCP_SA_JSON}
          project_id: ${GCP_PROJECT_ID}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${GCP_PROJECT_ID}
          service_account_key: ${GCP_SA_JSON}

      - name: Configure Docker to use the gcloud command-line tool as a credential helper
        run: gcloud auth configure-docker ${GCP_REGION}-docker.pkg.dev

      - name: Build, tag, and push image to Google Artifact Repository
        run: |
          docker buildx create --use
          docker buildx build --push \
            --tag ${GKE_REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/${GAR_REPOSITORY}/${IMAGE_NAME}:${IMAGE_TAG} \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache \
            .
          echo "IMAGE_URI=${GKE_REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/${GAR_REPOSITORY}/${IMAGE_NAME}:${IMAGE_TAG}" >> $GITHUB_ENV

      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${GKE_CLUSTER}
          location: ${GKE_REGION}

      - name: Deploy to GKE
        run: |
          kubectl apply -f ./worker-deployment.yaml
          kubectl rollout restart deployment worker

      - name: Wait for Deployment Rollout
        run: |
          kubectl rollout status deployment/worker --timeout=120s